---
- name: Clone and install Podman
  hosts: localhost
  become: yes
  tasks:
    - name: Clone Podman repository
      git:
        repo: https://github.com/containers/podman.git
        dest: /opt/podman
      register: git_clone_output

    - name: Change to Podman directory
      become: yes
      shell: cd /opt/podman
      args:
        chdir: /opt/podman
      when: git_clone_output.changed

    - name: Build Podman
      shell: make BUILDTAGS=""
      args:
        chdir: /opt/podman
      when: git_clone_output.changed

    - name: Install Podman
      shell: sudo make install
      args:
        chdir: /opt/podman
      when: git_clone_output.changed
