---
- name: Clone and build Podman from GitHub
  hosts: localhost
  become: yes

  tasks:
    - name: Install build dependencies
      dnf:
        name:
          - build-essential
          - git
          - golang
          - go-md2man
          - libglib2.0-dev
          - libostree-dev
          - libseccomp-dev
          - libdevmapper-dev
          - libgpgme-dev
          - libapparmor-dev
          - libprotobuf-dev
          - libprotobuf-c-dev
          - libprotobuf-glib-1.0-dev
          - libseccomp-dev
          - libselinux1-dev
          - pkg-config
          - runc
          - go-md2man
          - libbtrfs-dev

    - name: Clone Podman repository
      git:
        repo: https://github.com/containers/podman.git
        dest: /opt/podman

    - name: Change directory to Podman repository
      command:
        cmd: make BUILDTAGS="selinux seccomp"
        chdir: /opt/podman

    - name: Build Podman
      command:
        cmd: make BUILDTAGS="selinux seccomp"
        chdir: /opt/podman

    - name: Install Podman
      command:
        cmd: sudo make install PREFIX=/usr
        chdir: /opt/podman

