- name: Set GOPATH and build Go
  hosts: 127.0.0.1
  become: yes
  tasks:
    - name: Set GOPATH environment variable
      ansible.builtin.set_fact:
        GOPATH: ~/go

    - name: Clone Go repository
      shell: git clone https://go.googlesource.com/go $GOPATH

    - name: Change to Go source directory
      shell:
        cmd: pwd
        chdir: "{{ GOPATH }}/go/src"
   
    - name: Run all.bash script
      shell: ./all.bash

    - name: Update PATH
      shell: echo "export PATH=$GOPATH/bin:$PATH" >> ~/.bashrc
