---
- hosts: 127.0.0.1
  tasks:
  - name: Create GOPATH directory
    file:
      path: ~/go
      state: directory
  - name: Clone Go source code
    git:
      repo: https://go.googlesource.com/go
      dest: ~/go
  - name: Change directory to Go source code
    shell: cd ~/go
  - name: Change directory to src
    shell: cd src
  - name: Run all.bash
    shell: ./all.bash
  - name: Export PATH
    shell: export PATH=$GOPATH/bin:$PATH