---
- hosts: 127.0.0.1
  gather_facts: false
  become: false
  tasks:
    - name: Set GOPATH environment variable
      become: true
      shell: "echo 'export GOPATH=~/go' >> ~/.bashrc"

    - name: Clone Go repository
      git:
        repo: https://go.googlesource.com/go
        dest: "{{ lookup('env', 'GOPATH') }}/src"
        version: master
        accept_hostkey: yes

    - name: Build Go source code
      become: true
      shell: |
        cd "{{ lookup('env', 'GOPATH') }}/src/go/src"
        ./make.bash

    - name: Update PATH environment variable
      become: true
      shell: "echo 'export PATH=\"{{ lookup('env', 'GOPATH') }}/bin:$PATH\"' >> ~/.bashrc"



