---
- hosts: 127.0.0.1
  become: yes
  environment:
    GOPATH: "~/go"
  tasks:
    - name: Clone the Go repository
      git:
        repo: https://go.googlesource.com/go
        dest: "{{ lookup('env', 'GOPATH') }}/src/go"

