---
- name: Configure Go environment and build
  hosts: localhost
  become: yes
  tasks:
    - name: Set GOPATH environment variable
      lineinfile:
        path: ~/.bashrc
        line: "export GOPATH=~/go"
        insertafter: EOF

    - name: Clone Go repository
      git:
        repo: https://go.googlesource.com/go
        dest: "{{ lookup('env', 'GOPATH') }}/src/go"

    - name: Change to cloned directory
      command:
        cmd: ./all.bash
        chdir: "{{ lookup('env', 'GOPATH') }}/src/go/src"

    - name: Export Go bin directory to PATH
      lineinfile:
        path: ~/.bashrc
        line: "export PATH={{ lookup('env', 'GOPATH') }}/bin:$PATH"
        insertafter: EOF

