---
- hosts: your_host
  tasks:
    - name: Set GOPATH environment variable
      become: yes
      shell: export GOPATH=~/go

    - name: Clone the Go repository
      become: yes
      git:
        repo: https://go.googlesource.com/go
        dest: "{{ ansible_env.GOPATH }}"

    - name: Change directory to the Go source directory
      become: yes
      shell: cd "{{ ansible_env.GOPATH }}/src"

    - name: Run the all.bash script
      become: yes
      shell: ./all.bash
      args:
        chdir: "{{ ansible_env.GOPATH }}/src"

    - name: Add Go binaries to the PATH environment variable
      become: yes
      shell: export PATH="{{ ansible_env.GOPATH }}/bin:$PATH"
