---
- name: Configure Go environment and build
  hosts: 127.0.0.1
  become: yes
  tasks:
    - name: Set GOPATH environment variable
      lineinfile:
        path: ~/.bashrc
        line: "export GOPATH=~/go"
        insertafter: EOF

    - name: Clone Go repository
      git:
        repo: https://go.googlesource.com/go
        dest: "{{ lookup('env', 'GOPATH') }}/src/go"

    - name: Change to cloned directory
      shell:
        cmd: pwd
        args:
          chdir: "{{ lookup('env', 'GOPATH') }}/src/go/go"

    - name: Execute all.bash
      shell:
        cmd: ./all.bash
        args:
          chdir: "{{ lookup('env', 'GOPATH') }}/src/go/go"

    - name: Export Go bin directory to PATH
      lineinfile:
        path: ~/.bashrc
        line: "export PATH={{ lookup('env', 'GOPATH') }}/bin:$PATH"
        insertafter: EOF
