- name: Install podman from scratch
  hosts: 127.0.0.1
  become: yes
  tasks:
    - name: Install package(s)
      yum:
        name:
          - btrfs-progs-devel
          - conmon
          - containernetworking-plugins
          - containers-common
          - crun
          - device-mapper-devel
          - git
          - glib2-devel
          - glibc-static
          - go
          - golang-github-cpuguy83-md2man
          - gpgme-devel
          - iptables
          - libassuan-devel
          - libgpg-error-devel
          - libseccomp-devel
          - libselinux-devel
          - make
          - pkgconfig
        state: present
    - name: Set GOPATH environment variable
      command: echo "export GOPATH=~/go" >> ~/.bashrc
      changed_when: false
    - name: Clone go repository
      git:
        repo: https://go.googlesource.com/go
        dest: "{{ ansible_env.GOPATH }}"
        version: latest
      changed_when: false
    - name: Change directory to go
      command: cd "{{ ansible_env.GOPATH }}"
      changed_when: false
    - name: Run all.bash script
      command: ./all.bash
      changed_when: false
    - name: Add GOPATH/bin to PATH
      command: echo "export PATH={{ ansible_env.GOPATH }}/bin:$PATH" >> ~/.bashrc
      changed_when: false
    - name: Clone conmon repository
      git:
       repo: https://github.com/containers/conmon.git
       dest: conmon
       version: latest
      changed_when: false
    - name: Change directory to conmon
      command: cd conmon
      changed_when: false
    - name: Set GOCACHE environment variable
      command: export GOCACHE="$(mktemp -d)"
      changed_when: false
    - name: Build conmon
      command: make
      changed_when: false
    - name: Install conmon (requires sudo)
      become: yes
      command: make podman
      changed_when: false
    - name: Clone runc repository
      git:
       repo: https://github.com/opencontainers/runc.git
       dest: "{{ ansible_env.GOPATH }}/src/github.com/opencontainers/runc"
       version: latest
      changed_when: false
    - name: Change directory to runc
      command: cd "{{ ansible_env.GOPATH }}/src/github.com/opencontainers/runc"
      changed_when: false
    - name: Build runc with specific build tags
      command: make BUILDTAGS="selinux seccomp"
      changed_when: false
    - name: Copy runc to /usr/bin
      become: yes
      copy:
        src: "{{ ansible_env.GOPATH }}/src/github.com/opencontainers/runc/runc"
        dest: /usr/bin/runc
        mode: "0755"
      changed_when: false
    - name: Create /etc/containers directory
      become: yes
      file:
        path: /etc/containers
        state: directory
        mode: '0755'
      changed_when: false
    - name: Download registries.conf
      become: yes
      get_url:
        url: https://src.fedoraproject.org/rpms/containers-common/raw/main/f/registries.conf
        dest: /etc/containers/registries.conf
      changed_when: false
    - name: Download policy.json
      become: yes
      get_url:
        url: https://src.fedoraproject.org/rpms/containers-common/raw/main/f/default-policy.json
        dest: /etc/containers/policy.json
      changed_when: false
    - name: Clone podman repository
      git:
       repo: https://github.com/containers/podman.git
       dest: podman
       version: latest
      changed_when: false
    - name: Change directory to podman
      command: cd podman
      changed_when: false
    - name: Build podman with specific build tags
      command: make BUILDTAGS="selinux seccomp"
      changed_when: false
    - name: Install podman (requires sudo)
      become: yes
      command: make install PREFIX=/usr
      changed_when: false
    - name: Create ~/.ansible/roles directory
      become: yes
      file:
        path: ~/.ansible/roles
        state: directory
        mode: '0755'
      changed_when: false
    - name: Clone ansible-role-podman repository
      become: yes
      git:
        repo: https://github.com/alvistack/ansible-role-podman.git
        dest: ~/.ansible/roles/podman
        version: latest
      changed_when: false
    - name: Change directory to ansible-role-podman
      become: yes
      command: cd ~/.ansible/roles/podman
      changed_when: false
    - name: Upgrade pip and install requirements
      become: yes
      pip:
        name: "{{ item }}"
        state: latest
      with_file:
        - ~/.ansible/roles/podman/requirements.txt
      changed_when: false
    - name: Run molecule converge
      become: yes
      command: molecule converge
      args:
        chdir: ~/.ansible/roles/podman
      changed_when: false
    - name: Run molecule verify
      become: yes
      command: molecule verify
      args:
        chdir: ~/.ansible/roles/podman
      changed_when: false
