---
- name: Create directories and download files
  hosts: your_target_host
  become: true

  tasks:
    - name: Create /etc/containers directory
      file:
        path: /etc/containers
        state: directory
        mode: 0755

    - name: Download registries.conf file
      get_url:
        url: https://src.fedoraproject.org/rpms/containers-common/raw/main/f/registries.conf
        dest: /etc/containers/registries.conf
        mode: 0644

    - name: Download policy.json file
      get_url:
        url: https://src.fedoraproject.org/rpms/containers-common/raw/main/f/default-policy.json
        dest: /etc/containers/policy.json
        mode: 0644
