---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Clone conmon repository
      git:
        repo: https://github.com/containers/conmon
        dest: "{{ ansible_user_dir }}/conmon"

    - name: Change directory to conmon
      shell: cd "{{ ansible_user_dir }}/conmon"

    - name: Set GOCACHE environment variable
      shell: "export GOCACHE=\"$(mktemp -d)\""

    - name: Build conmon
      shell: make
      args:
        chdir: "{{ ansible_user_dir }}/conmon"

    - name: Install conmon
      shell: sudo make podman
      args:
        chdir: "{{ ansible_user_dir }}/conmon"
