---
- hosts: localhost
  gather_facts: false
  remote_user: rbanda
  become: true
  tasks:
    - name: Clone conmon repository
      git:
        repo: https://github.com/containers/conmon
        dest: "/home/rbanda/conmon"

    - name: Change directory to conmon
      shell: cd "/home/rbanda/conmon"

    - name: Set GOCACHE environment variable
      shell: "export GOCACHE=\"$(mktemp -d)\""

    - name: Build conmon
      shell: make
      args:
        chdir: "/home/rbanda/conmon"

    - name: Install conmon
      shell: sudo make podman
      args:
        chdir: "/home/rbanda/conmon"


