---
- name: Install packages using yum
  hosts: your_host
  become: yes
  tasks:
    - name: Install package(s)
      yum:
        name:
          - btrfs-progs-devel
          - conmon
          - containernetworking-plugins
          - containers-common
          - crun
          - device-mapper-devel
          - git
          - glib2-devel
          - glibc-static
          - go
          - golang-github-cpuguy83-md2man
          - gpgme-devel
          - iptables
          - libassuan-devel
          - libgpg-error-devel
          - libseccomp-devel
          - libselinux-devel
          - make
          - pkgconfig
        state: present
